# backend/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: parkguard
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    volumes:
      - pg_/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d parkguard"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pg_